### ISSUE TITLE
Kanban board - For review

### ISSUE THREAD

**Issue by Fikerte-T** [oluyaratosin123/Ruby-Capstone-Project#29]
- We are a team of three @Lockless404, @oluyaratosin123, @Fikerte-T 
- The link to the repo is `https://github.com/oluyaratosin123/Ruby-Capstone-Project`
-  tasks listed for: `Team member #1` is assigned to @Lockless404 
-  tasks listed for: `Team member #2` is assigned to @Fikerte-T 
- tasks listed for: `Team member #3` is assigned to @oluyaratosin123

**Comment by mikethreels** [comment]
Hi Team, 

Good job setting up the board, all the cards that are created have a very good description.!
However there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] some of the points mentioned in [the requirements list](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task) are not included, below I've added an image in which you can see an example of what I mean. because every person has 9 tasks in this list and there are 6 group tasks this means the total should add up to 33 cards for your group
![Screenshot 2022-03-21 151748](https://user-images.githubusercontent.com/39240820/159281540-50066be6-941c-4a4f-81d4-d5a3d317ea03.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elisha2kyakpo1** [comment]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Wishing you the best 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
